name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Despliegue de Liquibase iniciado"
          echo "Changesets 001-007 listos para desplegar"
          echo "Despliegue exitoso"